### PR TITLE
Change Main macro in Readme.md

### PR DESCRIPTION
**Pull request by alborq**
Maybe change on readme.md after fix of : #10

### CODE REVIEW

**Comment by sunli829** [comment]
The difference between `async_std::main` and `xactor::main` is that the former doesn't wait for all the actors to end, but the latter does. So there's no problem with that.

**Comment by alborq** [comment]
Rebased and made same change on ping exemple. ;)

**Comment by sunli829** [comment]
> Rebased and made same change on ping exemple. ;)

No, `xactor::main` is not required.

**Comment by alborq** [comment]
> No, xactor::main is not required.

Yes but it must work as same (+ wait all actor), and it's a bit confussing if xactor support tokio runtime and async-std. 

I thinks it's cleaner to show xactor::main everywhere than let understand to end user wish main it can use beetween : 
- xactor
- tokio
- async-std

If only one can be use on each case and support this complexity. 

if you disagree, i let you close this PR

**Comment by sunli829** [comment]
OK, you have a point! 😂

**Pull request merged**
